### ISSUE TITLE
Subfolders?

### ISSUE THREAD

**Issue by Hoopyy** [dsolonenko/titanius-launcher#10]
Hey, big fan of the launcher.

Is there a way to show subfolders in a rom directory? For instance, I have a few systems with romhacks or translations that I keep in a separate folder (eg "./Roms/snes/translations" or "./Roms/gba/hacks/Pokemon Hacks"). I noticed that multi-disc games use a folder system, but not sure if thats limited to .m3u

And a suggestion, more ways to filter/sort would be nice. Sorting by release date or rating, filtering by developer, publisher or number of players.

Another thing I had an issue with was favouriting a game, it would just hang when I tried to favourite something. I figured it was because my GBA gamelist.xml is something like 34000 lines long, but I tried it with a new 7 game Gamecube gamelist.xml and it hung in the same way. I understand this launcher is work in progress, just thought I'd mention that.

Thanks

**Comment by samwelnella** [comment]
What program are you using to generate your gamelist.xml? I was initially using Skyscraper but I found it doesn’t generate gamelist.xml files with proper subfolders. Switching to Skraper got subfolders working for me

**Comment by Hoopyy** [comment]
It would have been RetroBat that generated the gamelist.xml, it works fine in EmulationStation. Is there a specific format for the \<path> line that Titanius has to follow?

**Comment by Hoopyy** [comment]
Figured out my folder issue. gamelist.xml needs a \<folder> entry for each folder

**Comment by dsolonenko** [comment]
> Another thing I had an issue with was favouriting a game, it would just hang when I tried to favourite something. I figured it was because my GBA gamelist.xml is something like 34000 lines long, but I tried it with a new 7 game Gamecube gamelist.xml and it hung in the same way. I understand this launcher is work in progress, just thought I'd mention that.

Looks like I messed up the storage permission, can you please give the latest release a try.

**Comment by Hoopyy** [comment]
Getting errno = 13. Seems like it can't open gamelist.xml. I'm using Android 10 QKQ1.190828.002

**Comment by dsolonenko** [comment]
Have you granted the launcher access to all files? It should request that when starting. Or you can probably grant it manually in the Android standard app info for Titanius.

**Comment by Hoopyy** [comment]
Titanius has storage permissions, but I'm not sure if thats only for internal storage, all my roms are on an SD card.

**Comment by dsolonenko** [comment]
Storage permission should cover both. I have no issues on Odin which runs Android 10 as well. Maybe try uninstalling and reinstalling the latest 0.3.150?

**Comment by Hoopyy** [comment]
Still having the same issue. Not sure if I downloaded the latest 0.3.150 though, I just got it from the releases page, I don't need to build anything, right?

**Comment by dsolonenko** [comment]
Yeah, the latest from releases, no need to build anything. Btw you can see the version when you open the app settings (press `Start`).

Not sure what may be the issue here. Are you on MIUI?

**Comment by Hoopyy** [comment]
Yeah, MIUI Global 12.0.3

**Comment by dsolonenko** [comment]
Maybe something with the OS itself. You may follow the solution someone posted here https://forum.xda-developers.com/t/solved-write-access-to-ext-sd-card-denied.4481999/. Not perfect, but may work
> So under Developer Settings, there is an options to "Force Write Access to External SD for all Apps"

**Comment by Hoopyy** [comment]
Yeah I have no idea whats going on. I can write to the SD card when I ftp in or use a usb cable, but when I try to copy and paste from a file explorer on the phone it doesn't work. Seems like an issue on my end, sorry about that

**Comment by dsolonenko** [comment]
No worries, thanks for reporting, the storage permission was actually broken, the fix just did not work for MIUI.
