### ISSUE TITLE
SAF

### ISSUE THREAD

**Issue by theindifference** [dsolonenko/titanius-launcher#13]
-For Example ppsspp is set and granted Storage acess to my psp Rom folder.
Also in Titanius Launcher i added a Shared folder of the exact Same where i granted ppsspp also.
But the Roms wont start.."unable to run due to SAF restrictions"
It only opens the emulator itself.
This happens also with drastic, etc.
-Dolphin MMJR as an standalone Emulator wont Open either. I use MMJR 11505.

Can you Double Check the SAF or did i Make anything wrong.
In your readme was exact this written 
My device is a RP3+

**Comment by dsolonenko** [comment]
SAF issues are the most obscure to investigate, there are just too many things that can go wrong. I don't have RP3+ to verify, but I did test PPSSPP on G Cloud which runs Android 11 as well and it works just fine.

Can you please:
- Make sure that you run the latest Titanius Launcher and PPSSPP
- Remove all shared folders that you added in Titanius Launcher and add only `Roms/psp`
- Then try again, make sure that you open a rom directly from psp folder, not from any of its subfolders

**Comment by SisterVersio** [comment]
PPSSPP is fixed on the RP3+ by changing documenturi to path in metadata.json and recompiling the APK.
![image](https://github.com/dsolonenko/titanius-launcher/assets/25148746/5dbcd0c9-d9da-45bf-9af8-ab7b5bf895fe)
This is also true for GameCube with MMJR, I just set all of them to be path rather than documenturi

**Comment by dsolonenko** [comment]
That's fair, I guess the easies would be to release both configurations.

**Comment by theindifference** [comment]
Yes please, cause These 2 Emulators are missing for me to use this Great Launcher 🙂

**Comment by SisterVersio** [comment]
> That's fair, I guess the easies would be to release both configurations.

Please allow users to add and edit emulators without rebuilding the APK, Daijisho allows this in the settings to add emulators by their package name and launch flags.

Having to wait for the app to update to support individual apps and emulators will become extremely frustrating in the future
