### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by UzuCore** [dsolonenko/titanius-launcher#14]
device : wing second screen custom

resolution : 1240×1080

The logo is cut off like a video.
Please confirm.
thank you

https://github.com/dsolonenko/titanius-launcher/assets/5210242/90751e90-2eb7-4e1d-8545-e2d495ee163b

**Comment by dsolonenko** [comment]
Can you please give 0.3.159 a try and let me know

**Comment by UzuCore** [comment]
good good
very well.
