### ISSUE TITLE
Is multilingual support in the plan?

### ISSUE THREAD

**Issue by UzuCore** [dsolonenko/titanius-launcher#3]
Thank you for revealing a great program.

- Will you support languages other than English in the future?
- I need the game image option, if the image resolution is small the margins will look bad. (Ratio fixed/Fill screen)
- It would be nice if the directory could be displayed, but it seems that not many launchers support it.
- It would be nice if the size of the system logo of the default theme was a little smaller, but the logo is cut off on some devices. (g cloud)

thanks.

![KakaoTalk_20230508_183156365_04](https://user-images.githubusercontent.com/5210242/236791197-fd45a309-0a03-4aaa-8ee3-8fa1a291badc.jpg)
![KakaoTalk_20230508_183156365_01](https://user-images.githubusercontent.com/5210242/236791281-c6708c38-487b-4a77-8bbd-d1941b340e16.jpg)

**Comment by dsolonenko** [comment]
> Will you support languages other than English in the future?

Not something I have in an immediate todo lit. Maybe in the future with some community support.

> I need the game image option, if the image resolution is small the margins will look bad. (Ratio fixed/Fill screen)

The game screenshot should take as much space as possible. It can be that the scraped image has the black borders around? I noticed that sometimes Skraper produce images like that.

> It would be nice if the directory could be displayed, but it seems that not many launchers support it.

Folders are supported. They need to be properly scraped and included into gamelist.xml. Scraped does that by default.

> It would be nice if the size of the system logo of the default theme was a little smaller, but the logo is cut off on some devices. (g cloud)

Will have a look, thanks

**Comment by UzuCore** [comment]
There is no black border on the image. I'll attach it here.
![captcomm](https://user-images.githubusercontent.com/5210242/236991163-cef5360c-94f6-4f05-a64b-9065f4d746a8.png)

**Comment by UzuCore** [comment]
```
<game id="19269" source="ScreenScraper.fr">
    <path>./Korean Patch/Castlevania - Symphony of the Night (Korea).chd</path>
    <name>Castlevania : Symphony of the Night</name>
    <desc>As a descendant of Dracula, you must end the vampire bloodline. Can you rid the world of this unspeakable terror? Uncover the mystery of Castlevania and challenge an adventure as legendary as its name. Over 140 different enemies, bosses, and ghastly creatures. Awesome magical spells - transform into a bat, a wolf, or etheral mist. Hidden weapons, secrets, and characters...the largest Castlevania ever!</desc>
    <rating>0.95</rating>
    <releasedate>19971101T000000</releasedate>
    <developer>Konami</developer>
    <publisher>Konami</publisher>
    <genre>Platform-Action / Adventure-Action</genre>
    <players>1</players>
    <hash>BC45E325</hash>
    <image>./media/images/Korean Patch/Castlevania - Symphony of the Night (Korea).png</image>
    <thumbnail>./media/box2dfront/Korean Patch/Castlevania - Symphony of the Night (Korea).png</thumbnail>
    <video>./media/videos/Korean Patch/Castlevania - Symphony of the Night (Korea).mp4</video>
    <genreid>257</genreid>
  </game>

```
Games in the 'Korean Patch' subfolder are not displayed.
Scraping was done with a skraper.

**Comment by dsolonenko** [comment]
@UzuCore  Please have a look if you have folder entries in the `gamelist.xml`. Something like this:
```
<folder id="0" source="ScreenScraper.fr">
    <path>./Translations</path>
    <name>Translations (23)</name>
    <desc>Folder: gba/Translations 
Files: 23</desc>
    <image>./media/folders/Translations.png</image>
  </folder>
```
The folders should be at the top of the list, you have to go inside to see the games.

**Comment by UzuCore** [comment]
Oh, I scrapped it except for that part for my taste. Let me add.
Thank you for your kind feedback.
