### ISSUE TITLE
Shows every game from the gamelist even if not on the device

### ISSUE THREAD

**Issue by DynaMight1124** [dsolonenko/titanius-launcher#4]
Hi

Once again, thank you for the launcher. Some amazing features being added every week! One thing I noticed (that differs from my ES devices) is that it'll show every game in the gamelist.xml even if it doesnt exist on the device. 

Essentially on CD based consoles, I will usually have a bigger collection on my PC, scrape all the artwork etc then copy a selection of those games on to my devices depending on the device etc. On my previous ES devices, it's only shown the actual games on the device even if the gamelist contained many more entries however on Titanius, it shows every every game.

Is that something that can be adjusted? 

Thanks

**Comment by dsolonenko** [comment]
That can be adjusted. Let me have a look, hopefully it will not slow down the initial start.
