### ISSUE TITLE
Request for additional systems

### ISSUE THREAD

**Issue by jldgomes78** [dsolonenko/titanius-launcher#5]
Hello, would it be possible to add more systems?

I was thinking about the Amiga CD32 and the Amstrad GX4000.
Both of them run well with retroarch cores.

Others might have other "needs" or requests as well.

Thank you

**Comment by dsolonenko** [comment]
@jldgomes78 I can see Amstad GX4000 on https://pegasus-frontend.org/tools/metagen-android/ but there is no Amiga CD32. Which retroarch core supports that?

**Comment by jldgomes78** [comment]
Hello @dsolonenko GX4000 is indeed just a repackaged Amstrad CPC in a console style so the core will be caprice32, so just a copy of the CPC settings with new artwork should probably work.
The usual ES/batocera folder is "gx4000"

For CD32, its a very similar story, it's essentially a repackaged amiga in console form, so PUAE would work fine, I also believe a copy of the Amiga config should work, it just needs new artwork and a new folder. The folder name is usually "amigacd32"

Thank you!
