### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Tsudayfrt** [dsolonenko/titanius-launcher#7]
Hello! Does this app won't work without a computer to scrape your roms?

**Comment by DynaMight1124** [comment]
It requires a prescraped gamelist.xml to show your roms, best way to do that is on a PC/Laptop with a program called Skraper, theres a wiki here with suggested settings.

If you have other Emulation Station devices that have already scraped, it might be possible to grab the gamelist.xml plus any boxart etc and move it across to this. I believe it saves it in a different directory when it scrapes itself though.

**Comment by Tsudayfrt** [comment]
I see! Thank you
