### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by UzuCore** [dsolonenko/titanius-launcher#9]
안드로이드 tv에서도 설치되고 실행이 잘됩니다.
다만 설정->app에서는 찾을 수 있고 실행은 되지만
안드로이드 런처에서는 실행 아이콘을 찾을 수 없습니다.
daijisho의 경우에는 찾을 수 있습니다.
지원 해주세요, 감사합니다.

It is installed and runs well on Android TV.
However, you can find it in Settings->app and it runs.
I can't find the launch icon in android launcher.
In the case of daijisho, you can find it.
Please support, thanks.

**Comment by dsolonenko** [comment]
@UzuCore please give 0.3.148 a try and let me know

**Comment by UzuCore** [comment]
> @UzuCore please give 0.3.148 a try and let me know

perpect! thanks.

![20230526_141533](https://github.com/dsolonenko/titanius-launcher/assets/5210242/605a2901-40c8-4659-880c-b047cc3d8113)
![Screenshot_20230526_141603_Gallery](https://github.com/dsolonenko/titanius-launcher/assets/5210242/586df3d7-7d27-4d56-971b-663253f958e5)

**Comment by UzuCore** [comment]
How about not displaying the battery when the battery is at 0%?
0% battery is displayed on the top right of the TV.
